{% set name = "miepython" %}
{% set version = "3.0.0" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/miepython-{{ version }}.tar.gz
  sha256: e1325aadec146d69651b6734a1978b11f2bc9ad3db3568b404ce979ff0fc0fc9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numba
    - numpy

test:
  imports:
    - miepython
  requires:
    - python {{ python_min }}
    - pytest
  source_files:
    - tests/test_mie.py
  commands:
    - pytest tests/test_mie.py

about:
  home: https://github.com/scottprahl/miepython.git
  summary: |
    A pure Python module to calculate light scattering for
    non-absorbing, partially-absorbing, or perfectly-conducting spheres. Mie
    theory is used, following the procedure described by Wiscombe
    <http://opensky.ucar.edu/islandora/object/technotes:232>. This code has
    been validated against his results. 

    This code provides functions for calculating the extinction efficiency, 
    scattering efficiency, backscattering, and scattering asymmetry. Moreover, 
    a set of angles can be given to calculate the scattering for a sphere at 
    each of those angles.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
  doc_url: https://miepython.readthedocs.io/
  dev_url: https://github.com/scottprahl/miepython

extra:
  recipe-maintainers:
    - scottprahl
