{% set name = "miepython" %}
{% set version = "2.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/miepython-{{ version }}.tar.gz
  sha256: 3e13b36949db0aaf72787dffd1003f936cb72c062a9ca209cfa5982799252dd2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - matplotlib-base
    - numba
    - numpy
    - python >=3.9

test:
  imports:
    - miepython
  requires:
    - pytest
  source_files:
    - tests/test_jit.py
    - tests/test_nojit.py
  commands:
    - pytest tests/test_nojit.py tests/test_jit.py
    
about:
  home: https://github.com/scottprahl/miepython.git
  summary: |
    A pure Python module to calculate light scattering for
    non-absorbing, partially-absorbing, or perfectly-conducting spheres. Mie
    theory is used, following the procedure described by Wiscombe
    <http://opensky.ucar.edu/islandora/object/technotes:232>. This code has
    been validated against his results. 

    This code provides functions for calculating the extinction efficiency, 
    scattering efficiency, backscattering, and scattering asymmetry. Moreover, 
    a set of angles can be given to calculate the scattering for a sphere at 
    each of those angles.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
  doc_url: https://miepython.readthedocs.io/
  dev_url: https://github.com/scottprahl/miepython


extra:
  recipe-maintainers:
    - scottprahl
